### ISSUE TITLE
Code does not match the paper

### ISSUE THREAD

**Issue by manis404** [jgmakin/machine_learning#1]
According to: [https://www.nature.com/articles/s41593-020-0608-8]

> 

The code used to train and test the encoder–decoders is available at https://github.com/jgmakin/machine_learning. Code used to assemble data and generate figures is also available upon reasonable request; please contact J.G.M. via e-mail with any inquiries.

>

However, it seems that this repo does not publicly contain any runnable code yet.

**Comment by jgmakin** [comment]
I'm not sure what you mean: the code is all "runnable" and public.  But you may have an easier time getting started from here:

https://github.com/jgmakin/ecog2txt
